{"uuid": "a68b4e73-0db0-4a27-b3b1-7b2f8b9bf24e", "children": ["4f283921-17e1-4049-9971-40167c1f2920"], "befores": [{"name": "_xunit_setup_class_fixture_TestUiCatelog", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104a2bc40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1125, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 880, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/python.py\", line 786, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/python.py\", line 714, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/pauline/PycharmProjects/test/Ios_Test/case/test_uicatelog.py\", line 17, in setup_class\n    self.main = self.app.start().goto_main()\n  File \"/Users/pauline/PycharmProjects/test/Ios_Test/base/app.py\", line 38, in start\n    self.driver = webdriver.Remote(\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/appium/webdriver/webdriver.py\", line 229, in __init__\n    super().__init__(\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/appium/webdriver/webdriver.py\", line 320, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/urllib3/_request_methods.py\", line 144, in request\n    return self.request_encode_body(\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/urllib3/_request_methods.py\", line 279, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n"}, "start": 1720073440171, "stop": 1720073440173}], "start": 1720073440171, "stop": 1720073440293}