{"uuid": "8aebe588-4152-4692-913e-4969f9941435", "children": ["ab671109-adc1-4764-a4de-c881ee6b6b8f"], "befores": [{"name": "_xunit_setup_class_fixture_TestUiCatelog", "status": "broken", "statusDetails": {"message": "TypeError: not all arguments converted during string formatting\n", "trace": "  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1125, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 880, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/python.py\", line 786, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/python.py\", line 714, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/pauline/PycharmProjects/test/Ios_Test/case/test_uicatelog.py\", line 17, in setup_class\n    self.main = self.app.start().goto_main()\n  File \"/Users/pauline/PycharmProjects/test/Ios_Test/base/app.py\", line 38, in start\n    logger.info(\"此时driver是个对象并且拿到了: \", self.driver)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py\", line 1446, in info\n    self._log(INFO, msg, args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py\", line 1589, in _log\n    self.handle(record)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py\", line 1599, in handle\n    self.callHandlers(record)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py\", line 1661, in callHandlers\n    hdlr.handle(record)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py\", line 952, in handle\n    self.emit(record)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/logging.py\", line 388, in emit\n    super().emit(record)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py\", line 1091, in emit\n    self.handleError(record)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py\", line 1083, in emit\n    msg = self.format(record)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py\", line 927, in format\n    return fmt.format(record)\n  File \"/Users/pauline/PycharmProjects/test/android_test/.venv/lib/python3.9/site-packages/_pytest/logging.py\", line 141, in format\n    return super().format(record)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py\", line 663, in format\n    record.message = record.getMessage()\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py\", line 367, in getMessage\n    msg = msg % self.args\n"}, "start": 1720071839878, "stop": 1720071842211}], "start": 1720071839878, "stop": 1720071842341}